[package]
name = "encap-video"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
avid-core.workspace = true
encap-core = { path = "../encap-core" }
encap-ffmpeg = { path = "../encap-ffmpeg" }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
