[package]
name = "encap-ffmpeg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
avid-core.workspace = true
encap-core = { path = "../encap-core" }
tempfile.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
